### ISSUE TITLE
Variáveis de Ambiente Sensíveis Expostas

### ISSUE THREAD

**Issue by Kc1t** [BrunoOlv10/crud-firebase-v2#1]
Seu repositório contém variáveis de ambiente sensíveis expostas no arquivo .env. Para evitar expor informações confidenciais, não esqueça de colocar o .env no seu .gitignore.

**Comment by BrunoOlv10** [comment]
Muito obg cara! Agradeço pelo aviso.

**Comment by BrunoOlv10** [comment]
Muito obg cara! Agradeço pelo aviso.
